# Resources/config/controllers.yml
services:

    WBW\Bundle\SmsModeBundle\Controller\DefaultController:
        alias:  "wbw.smsmode.controller.smsmode.default"
        public: true

    wbw.smsmode.controller.smsmode.default:
        class: WBW\Bundle\SmsModeBundle\Controller\DefaultController
        calls:
            - [ "setContainer", [ "@service_container" ] ]
