# Resources/config/controllers.yml
services:

    WBW\Bundle\SmsModeBundle\Controller\DefaultController:
        alias:  "wbw.smsmode.controller.default"
        public: true

    wbw.smsmode.controller.default:
        class:  WBW\Bundle\SmsModeBundle\Controller\DefaultController
        public: true
        calls:
            - [ "setContainer", [ "@service_container" ] ]
        tags:
            - { name: "container.service_subscriber" }
