# Resources/config/controllers.yml
services:

    WBW\Bundle\SmsModeBundle\Controller\DefaultController:
        alias: "wbw.smsmode.controller.smsmode.default"

    wbw.smsmode.controller.smsmode.default:
        class:  WBW\Bundle\SmsModeBundle\Controller\DefaultController
        public: true
        calls:
            - [ "setContainer", [ "@service_container" ] ]
