# Resources/config/routing/smsmode.yml
wbw_smsmode_delivery_report_callback:
    path: "/delivery-report-callback"
    defaults: { _controller: "WBW\\Bundle\\SMSModeBundle\\Controller\\SMSModeController::deliveryReportCallbackAction" }
    methods: [ "GET" ]

wbw_smsmode_sms_reply_callback:
    path: "/sms-reply-callback"
    defaults: { _controller: "WBW\\Bundle\\SMSModeBundle\\Controller\\SMSModeController::smsReplyCallbackAction" }
    methods: [ "GET" ]
