# Resources/config/routing/smsmode.yml
wbw_smsmode_delivery_report_callback:
    path: "/delivery-report-callback"
    defaults: { _controller: "WBWSMSModeBundle:SMSMode:deliveryReportCallback" }
    methods: [ "GET" ]

wbw_smsmode_sms_reply_callback:
    path: "/sms-reply-callback"
    defaults: { _controller: "WBWSMSModeBundle:SMSMode:smsReplyCallback" }
    methods: [ "GET" ]
